### ISSUE TITLE
[Feat] 데이터 파일 읽기, 무결성 검사, 쓰기 함수 구현

### ISSUE THREAD

**Issue by leehe228** [rich-hyun/Make_Library_Server#15]
## 🛠 Issue
데이터 파일 읽기, 무결성 검사, 쓰기 함수 구현

## 📝 To-do
- [ ] 데이터 파일 읽기 구현
- [ ] 데이터 파일 무결성 검사 구현
- [ ] 데이터 파일 쓰기 함수 구현
