### ISSUE TITLE
[Feat] 현재날짜 입력 및 날짜 무결성 검사 구현

### ISSUE THREAD

**Issue by leehe228** [rich-hyun/Make_Library_Server#47]
## 🛠 Issue
메인프롬프트 현재날짜 입력 및 날짜 무결성 검사 구현

## 📝 To-do

- [x] 현재 날짜 입력 함수 구현
- [x] 입력받은 현재 날짜 데이터에 따른 무결성 검사 구현
- [x] 기존 파일 무결성 검사 함수 수정
